"""report_generate - Generate test reports in markdown/html format."""

import json
import logging
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, List, Optional

logger = logging.getLogger(__name__)


def report_generate_handler(
    results: str = "",
    format: str = "markdown",
    output: str = "test-report.md",
    project: str = "",
    **_kwargs,
) -> str:
    """Generate a test report from results.

    Args:
        results: Test results as JSON string or raw output
        format: Output format: 'markdown' or 'html'
        output: Output file path (relative to cwd)
        project: Project name for the report header

    Returns:
        Path to generated report file.
    """
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    project_name = project or "Project"

    # Parse results if JSON
    parsed = None
    if results:
        try:
            parsed = json.loads(results)
        except (json.JSONDecodeError, TypeError):
            pass

    if format == "markdown":
        content = _generate_markdown(parsed or results, project_name, timestamp)
    else:
        content = _generate_html(parsed or results, project_name, timestamp)

    # Write to file
    output_path = Path(output)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(content, encoding="utf-8")

    return f"✅ Report generated: {output_path.resolve()}\n\nPreview:\n{content[:1000]}..."


def _generate_markdown(results: Any, project: str, timestamp: str) -> str:
    """Generate a markdown test report."""
    if isinstance(results, dict):
        passed = results.get("passed", 0)
        failed = results.get("failed", 0)
        skipped = results.get("skipped", 0)
        total = passed + failed + skipped
        coverage = results.get("coverage", "N/A")
        failures = results.get("failures", [])
        status = "✅ PASSED" if failed == 0 else "❌ FAILED"
    else:
        # Raw string results
        return f"""# Test Report — {project}
**Date**: {timestamp}

## Raw Results

```
{results}
```
"""

    lines = [
        f"# Test Report — {project}",
        f"**Date**: {timestamp}",
        f"**Status**: {status}",
        "",
        "## Overview",
        f"| Metric | Value |",
        f"|--------|-------|",
        f"| Total | {total} |",
        f"| Passed | {passed} ✅ |",
        f"| Failed | {failed} ❌ |",
        f"| Skipped | {skipped} ⏭️ |",
        f"| Coverage | {coverage} |",
        "",
    ]

    if failures:
        lines.append("## Failed Tests")
        for f in failures:
            name = f.get("name", "Unknown")
            error = f.get("error", "")
            analysis = f.get("analysis", "")
            suggestion = f.get("suggestion", "")
            lines.extend([
                f"### ❌ {name}",
                f"**Error**: `{error}`",
            ])
            if analysis:
                lines.append(f"**Analysis**: {analysis}")
            if suggestion:
                lines.append(f"**Suggestion**: {suggestion}")
            lines.append("")

    lines.extend([
        "## Risk Assessment",
        "- Review failed tests before merging",
        "- High-risk tests (billing/security) require manual confirmation",
        "",
        "---",
        f"*Generated by ProAgent Test Agent*",
    ])

    return "\n".join(lines)


def _generate_html(results: Any, project: str, timestamp: str) -> str:
    """Generate a minimal HTML test report."""
    md_content = _generate_markdown(results, project, timestamp)
    # Simple HTML wrapper
    return f"""<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>Test Report — {project}</title>
<style>
body {{ font-family: sans-serif; max-width: 900px; margin: 40px auto; padding: 0 20px; }}
pre {{ background: #f5f5f5; padding: 15px; border-radius: 4px; overflow-x: auto; }}
table {{ border-collapse: collapse; width: 100%; }}
th, td {{ border: 1px solid #ddd; padding: 8px; text-align: left; }}
th {{ background: #f2f2f2; }}
</style>
</head>
<body>
<pre>{md_content}</pre>
</body>
</html>"""
